source 'https://rubygems.org'

ruby '2.1.1'

gem 'rails', '4.1.0'
gem 'pg'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'

group :development, :test do
  gem 'spring'
  gem 'byebug'
  gem 'pry'
  gem 'pry-byebug'
  gem 'spring-commands-rspec'
  gem 'quiet_assets'
end

group :test do
  gem 'rspec-rails'
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'database_cleaner'
  gem 'selenium-webdriver'
end
